import {
  Grain,
  PersonAdd,
  AccountCircleOutlined,
  HomeOutlined,
  HelpOutline,
  ExitToAppRounded,
  MovieFilter,
  ShoppingCartOutlined,
  TvOutlined,
  ExpandLess,
  ExpandMore,
  AssessmentOutlined,
  Create,
  AttachFile,
  Http,
  FolderOutlined,
  Check,
  WhatshotOutlined,
  MonetizationOn,
  MailOutlined,
  PermMedia,
  FilterList,
  ArrowBack,
  ClearOutlined,
  Cancel,
  Close,
  Category,
  Apps,
  List,
  DragHandle,
  Loyalty,
  PhotoCamera,
  KeyboardArrowDownOutlined,
  KeyboardArrowUp,
  ChevronLeftRounded,
  ChevronRightRounded,
  VisibilityOutlined,
  WatchLaterOutlined,
  Archive,
  Storefront,
  Restore,
  MaleOutlined,
  FemaleOutlined,
  PhoneEnabledOutlined,
  MapOutlined,
  LanguageOutlined,
  FullscreenOutlined,
  PriorityHigh,
  MoreVert,
  Circle,
  ArrowDownward,
  ArrowUpward,
  ReportProblem
} from '@mui/icons-material';

// BrandDeal Icons
import CachedIcon from '@mui/icons-material/Cached';
import FindInPageOutlinedIcon from '@mui/icons-material/FindInPageOutlined';
import VerifiedUserIcon from '@mui/icons-material/VerifiedUser';
import LocalShippingOutlinedIcon from '@mui/icons-material/LocalShippingOutlined';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import CreditCardOutlinedIcon from '@mui/icons-material/CreditCardOutlined';
import TaskAltIcon from '@mui/icons-material/TaskAlt';

// Local Icons

export const icons = {
  TalentDirectory: Grain,
  AddPerson: PersonAdd,
  Home: HomeOutlined,
  Support: HelpOutline,
  AccountCircleOutlined, // @TODO change name of this icon
  Logout: ExitToAppRounded,
  Influencer: MovieFilter,
  Show: TvOutlined,
  Product: ShoppingCartOutlined,
  Collapsed: ExpandLess,
  Expanded: ExpandMore,
  Reports: AssessmentOutlined,
  Pencil: Create,
  Paperclip: AttachFile,
  Url: Http,
  Folder: FolderOutlined,
  CheckMark: Check,
  Hot: WhatshotOutlined,
  Mail: MailOutlined,
  Money: MonetizationOn,
  Media: PermMedia,
  Filter: FilterList,
  BackArrow: ArrowBack,
  X: ClearOutlined,
  Category,
  closeRemove: Cancel,
  Close,
  Grid: Apps,
  List,
  ArrowDown: KeyboardArrowDownOutlined,
  ArrowUp: KeyboardArrowUp,
  DateToolbarPrev: ChevronLeftRounded,
  DateToolbarNext: ChevronRightRounded,
  VisibilityOutlined,
  WatchLaterOutlined,
  Archive,
  Storefront,
  Restore,
  FindInPageOutlinedIcon,
  VerifiedUserIcon,
  LocalShippingOutlinedIcon,
  VisibilityOutlinedIcon,
  CreditCardOutlinedIcon,
  Male: MaleOutlined,
  Female: FemaleOutlined,
  Phone: PhoneEnabledOutlined,
  Map: MapOutlined,
  Language: LanguageOutlined,
  FullscreenOutlined: FullscreenOutlined,
  MoreVert: MoreVert,
  CachedIcon,
  Circle,
  PriorityHigh,
  ArrowDownward,
  ArrowUpward,
  TaskAltIcon,
  ReportProblem
};
